### PR TITLE
translate zh init

### PR DESCRIPTION
**Pull request by godhth**
## Summary

Brief explanation of the proposed changes.

## Basic example

Include a basic example, screenshots, or links.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Checks

- [ ] Read [Create a Pull Request](https://acmestack.org/docs/contributing-guide)
- [ ] Supports all screen sizes (if relevant)
- [ ] Supports both light and dark mode (if relevant)
- [ ] Passes `npm run test`

### CODE REVIEW

**Comment by qicz** [comment]
@godhth please view and sign cla

**Comment by godhth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by qicz — APPROVED** [review]
LGTM

**Comment by qicz** [comment]
fix #1

**Pull request merged**
